name: rnaseq-processing
channels:
  - bioconda
  - conda-forge
dependencies:
  - bioconda::snakemake=5.20.1
  - bioconda::kallisto=0.46.2
  - conda-forge::pandas=1.1.0
  - bioconductor-deseq2
  - bioconductor-tximeta
  - bioconductor-rhdf5
  - bioconductor-rtracklayer
